"""Add user_id to review

Revision ID: 4d1134228d08
Revises: bda6627d4d2f
Create Date: 2025-06-20 10:43:51.991211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1134228d08'
down_revision: Union[str, None] = 'bda6627d4d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'])
    op.alter_column('user', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'user_id')
    # ### end Alembic commands ###
