"""Added correct_text to review table

Revision ID: d1dc9bb2f8ad
Revises: af9ff8283da2
Create Date: 2025-06-02 09:43:42.530428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1dc9bb2f8ad'
down_revision: Union[str, None] = 'af9ff8283da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('corrected_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'corrected_text')
    # ### end Alembic commands ###
