name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: review_analyzer_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/review_analyzer_test
      SECRET_KEY: test-secret
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: review_analyzer_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv & Python 3.10
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.10'
          enable-cache: true

      - name: Show versions (debug)
        run: |
          uv --version
          python --version

      - name: Sync deps (prod + dev)
        working-directory: backend
        run: uv sync --locked --extra dev

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 1
          done

      - name: Run Alembic migrations
        working-directory: backend
        run: uv run alembic upgrade head

      - name: Run Backend Tests
        working-directory: backend
        run: uv run python -m pytest

      - name: Prune uv cache
        run: uv cache prune --ci
